services:
  postgres:
    image: postgres:13.18
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - airflow-net

  mongodb:
    image: mongo:8.0.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=impactu
    networks:
      - airflow-net

  airflow-api-server:
    build: .
    command: api-server
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment: &airflow-common-env
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__INTERNAL_API_SECRET=${AIRFLOW__CORE__INTERNAL_API_SECRET}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__INTERNAL_API_URL=http://airflow-api-server:8080/execution/
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=True
      - AIRFLOW_CONN_MONGODB_DEFAULT=mongo://mongodb:27017/impactu
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./extract:/opt/airflow/extract
    ports:
      - "8080:8080"
    networks:
      - airflow-net

  airflow-scheduler:
    build: .
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-api-server:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-common-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./extract:/opt/airflow/extract
    networks:
      - airflow-net

  airflow-dag-processor:
    build: .
    command: dag-processor
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-common-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./extract:/opt/airflow/extract
    networks:
      - airflow-net

  airflow-triggerer:
    build: .
    command: triggerer
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-common-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    networks:
      - airflow-net

  airflow-init:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment: *airflow-common-env
    command: bash -c "airflow db migrate"
    networks:
      - airflow-net

networks:
  airflow-net:
    driver: bridge
